name: Publish package
on: 
  push:
    branches:
      - main
jobs:
  release:
    if: github.repository == 'TuentyFaiv/svelte-form'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Build library
        run: pn build --filter @tuentyfaiv/svelte-form

      - name: Publish package
        run: pnpm publish --filter @tuentyfaiv/svelte-form --access=publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}