name: Publish package to npmjs
on: release
jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable
      - run: corepack prepare pnpm@latest --activate
      - run: pnpm i
      - run: pnpm build
      - run: cd ./package
      - run: npm publish --access=publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}