name: Publish extra packages
on: 
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release-builtin:
    if: github.repository == 'TuentyFaiv/svelte-form' && contains(github.event.pull_request.head.ref, 'builtin-v') && github.event.pull_request.merged == true
    name: Release Built-in forms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Build @faivform/builtin
        run: pnpm build --filter @faivform/builtin

      - name: Publish built-in forms package
        run: pnpm publish --filter @faivform/builtin --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_BUILTIN_TOKEN }}