name: Check before merge to main
on:
  pull_request:
    branch: master
jobs:
  linter:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: corepack enabled
      - run: corepack prepare pnpm@latest --activate
      - run: pnpm i
      - run: pnpm lint